export const CARS=[
    {
        "id":1,
        "COLOR":"Red",
        "brand":"Toyota",
        "model":"Corolla"
    },
    {
        "id":2,
        "COLOR":"Blue",
        "brand":"Toyota",
        "model":"Camry"
    },
    {
        "id":3,
        "COLOR":"Black",
        "brand":"Toyota",
        "model":"Prius"
    },
    {
        "id":4,
        "COLOR":"White",
        "brand":"Toyota",
        "model":"Rav4"
    },
    {
        "id":5,
        "COLOR":"Red",
        "brand":"Toyota",
        "model":"Corolla"
    },
    {
        "id":6,
        "COLOR":"Blue",
        "brand":"Toyota",
        "model":"Camry"
    }
]